apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: basic
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-f0ec0466-d9fb-42f6-adb2-65239605833a:
      events:
        - push
      repositories:
        - owner: nightmar39
          names:
            - source-test
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/csdp-june-charizard/basic/github-f0ec0466-d9fb-42f6-adb2-65239605833a
        url: https://charizard-csdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
