apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: basic
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-f0ec0466-d9fb-42f6-adb2-65239605833a
      eventName: github-f0ec0466-d9fb-42f6-adb2-65239605833a
      eventSourceName: basic
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: helloworld
        conditions: github-f0ec0466-d9fb-42f6-adb2-65239605833a
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: basic-helloworld-
              spec:
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters: []
