apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata: 
  name: hello-world-test
spec: 
  entrypoint: whalesay
  templates:
    - name: whalesay
      container: 
        image: docker/whalesay
        command: [cowsay]
        args: ["Hello from my first pipeline"]